@include('vue.scripts.general')
@include('vue.scripts.ajax')
@include('vue.scripts.general')

@include('vue.components.button_group')
@include('vue.components.datepicker')
@include('vue.components.delete')
@include('vue.components.edit_row')
@include('vue.components.icheck')
@include('vue.components.modal')
@include('vue.components.select2')
@include('vue.components.show_row')
@include('vue.components.standard_form')
@include('vue.components.table_all')
@include('vue.components.table_pager')
@include('vue.components.table_searcher')
@include('vue.components.table_pager')

@include('vue.mixins.table_paging')
@include('vue.mixins.table_searching')
@include('vue.mixins.table_sorting')